---
- name: Generate configuration file from template
  ansible.builtin.template:
    src: "{{ role_name }}.loki.alloy.j2"
    dest: "{{ alloy_dir }}/{{ config_name | default('write') }}.loki.alloy"
    mode: "{{ config_permissions }}"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
  notify:
    - Verify Grafana Alloy
